%% clear the workspace variables and close all figures
clear all
clc
close all
%% Load the map
load map1
about map
%% plot the map
plot(Bug2(map))
%% Initial position and heading of the robot
p_init=[50 30]; % [x,y]
%% Goal location of the robot 
p_goal=[20 5]; % [x,y]

%% Define the desired path 
obstacle=1; %--------------------------set obstacle here
if obstacle == 0
    path=[ p_init;...
           15 40 ;...
           20 65 ;...
           50 68 ;...
           58 96 ;...
           70 96 ;...
           83 60 ;...
           83 3 ;...
           p_goal
        ];
else
    path=[ p_init;...
       15 40 ;...
       20 65 ;...
       50 68 ;...
       58 96 ;...
       70 96 ;...
       83 60 ;...
       100 60 ;...
       83 3 ;...
       p_goal
    ];
end


%% Genrate trajectory
QDMAX = [20,20]; %axis speed limits
Q0 = path(1,:); %initial axis coordinates
DT = 0.2;
traj = mstraj(path, QDMAX, [], Q0, DT, 0);
%% Plot the path
obstacle=obstacle; %0 when there is no door to block the way, 1 the door will be on
animatepath(traj,DT,obstacle)
hold on
plot(path(:,1), path(:,2))